# This is a basic workflow to help you get started with actions

name: CI

# Controls when the workflow will run 
on:
  #Trigger the workflow on push or pull request events but only for main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflo manually from the Action tab
  workflow_dispatch:

# A workflow run is madeup of one or more jobs that can run sequentially or parallel
jobs:
  #This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{secrets.HF}}
        run: git remote add space https://jatinsingh2012:$HF@huggingface.co/spaces/jatinsingh2012/demo2
      - name: Push to hub
        env:
          HF: ${{secrets.HF}}
        run: git push --force https://jatinsingh2012:$HF@huggingface.co/spaces/jatinsingh2012/demo2
        
    
    
